# Site settings
title: Miquel de la Fuente | Portfolio
email: mfuente@kumavolt.dev
description: Portfolio of Miquel de la Fuente AKA KumaVolt. Connect with me on Github, Instagram, Twitter and Linkedin under the same username KumaVolt.
baseurl: /
url: https://kumavolt.dev
twitter_username: KumaVolt
github_username: KumaVolt
