# Site settings
title: Miquel de la Fuente | Portfolio
email: miquelakshay@gmail.com
description: Portfolio of Miquel de la Fuente AKA KumaVolt. Also find me at Github, Instagram, Twitter and Linkedin under the same username.
baseurl: /
url: https://kumavolt.dev
twitter_username: KumaVolt
github_username: KumaVolt
